# Example license file, real end-to-end test fixture (not a placeholder).
#
# Signed with the development private key whose public half is embedded
# in `src/license.rs` as `LICENSE_PUBLIC_KEY_HEX`, using:
#
#   cargo run --bin tri_sync_node_license_tool -- sign \
#     --private-key <dev key, discarded from this machine after signing> \
#     --org "TriSync Example Org" --max-nodes 5 --expiry 2030-01-01
#
# The private key was generated for this repository with
# `tri_sync_node_license_tool generate-key` and discarded from this
# machine after signing - it is not, and will not be, committed
# anywhere. Before any license is issued to a real customer,
# `LICENSE_PUBLIC_KEY_HEX` must be replaced with a real production
# public key generated independently by whoever issues licenses, and
# licenses signed with its matching private key, which stays with them.
#
# `features` is left empty deliberately, not merely as a placeholder:
# nothing in `tri_sync_node` currently gates behavior on a specific
# feature name (only `max_nodes` is enforced - see
# `License::has_feature`'s doc comment in src/license.rs for the
# honest current status), so this fixture doesn't claim otherwise. An
# earlier version of this file listed `chain_crypto`/`chain_weighted`/
# `http_api` here, which were actually the unrelated single-process
# simulation binaries' names, not real feature flags of this product -
# corrected once that confusion was noticed, not left as a precedent.
#
# The signature covers "org|max_nodes|sorted,features|expiry" - see
# `canonical_string` in src/license.rs.

org = "TriSync Example Org"
max_nodes = 5
features = []
expiry = "2030-01-01"
signature = "9591053fef85cff4723d5a162ef55faaee9a829e6f42cbcda0a7bec3a74d3f8dd5abf976bfd1212262ad661f7917bcbe9d1f2daa53a9285e9b106a05bcf1d803"
